name: run-slide-command
on:
  repository_dispatch:
    types: [run-slide-command]
jobs:
  runSlide:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name || github.event.client_payload.github.payload.repository.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref || 'master' }}

      - name: Build and run
        id: run
        run: |
          cargo build
          export SLIDE_OUT="$({./target/debug/slide ${{ github.event.client_payload.slash_command.args }} } 2>&1)"
          echo ::set-output name=slide-out::$SLIDE_OUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            > slide ${{ github.event.client_payload.slash_command.args }} (${{ github.event.client_payload.github.payload.comment.html_url }})

            ```
            ${{ steps.run.outputs.slide-out }}
            ```

            [Command run output][1]
            [1]: ${{ steps.vars.outputs.run-url }}
