name: slide-command
on:
  repository_dispatch:
    types: [slide-command]
jobs:
  slide:
    runs-on: ubuntu-latest
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.SLIDE_WORKFLOWS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: eyes

      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SLIDE_WORKFLOWS_TOKEN }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name || github.event.client_payload.github.payload.repository.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref || 'master' }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      
      - name: Cache Rust
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build and run
        id: run
        run: |
          cargo build
          target/debug/slide ${{ github.event.client_payload.slash_command.args }} &> out.slide || true
          SLIDE_OUT=$(cat out.slide)
          JSON_STRING=$(jq -cn --arg out "$SLIDE_OUT" '{slide_out: $out}')
          echo "::set-output name=matrix::$JSON_STRING"
          
      - name: Check JSON
        run: echo ${{ steps.run.outputs.matrix }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.SLIDE_WORKFLOWS_TOKEN }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            > slide ${{ github.event.client_payload.slash_command.args }} (${{ github.event.client_payload.github.payload.comment.html_url }})

            ```
            ${{ fromJson(steps.run.outputs.matrix).slide_out }}
            ```

            [Command run output][1]

            [1]: https://github.com/ayazhafiz/slide-workflows/actions/runs/${{ github.run_id }}
